name: keithbelfast
favicon: null
layout_spectrum: 0.2570666540414095
typography_spectrum: 0.57739501981996
title: The grid.io test site of Keith Anderson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74772841-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffa779'
    - '#7d8d73'
    - '#056269'
    - '#65725e'
    - '#ee6751'
  brandStrength: 0.125
  lightness: 0.8583924563135952
  saturation: 1
  rhythmicContrast: 0.2747380738146603
purpose: []
